default_platform(:ios)

platform :ios do
  desc "Build and upload app to TestApp.io"
  lane :beta do

    match(
      type: "adhoc",
      readonly: false,
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: ENV["MATCH_GIT_PRIVATE_TOKEN"]
    )

    build_app(
      scheme: "TestCiApp",
      export_method: "ad-hoc"
    )

    upload_to_testappio(
      api_token: ENV["TESTAPPIO_API_TOKEN"],
      app_id: "9QorGVmE7M"
    )
  end
end
