default_platform(:ios)

platform :ios do
  desc "Push to TestApp.io"
  lane :beta do
    puts "🔐 Using uploaded AuthKey.p8 file from Jenkins"

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_FILE"]
    )

    match(
      type: "adhoc",
      api_key: api_key,
      git_url: "https://github.com/MohammedHamiid/ios-certificates.git",
      app_identifier: ["com.benhamid.TestCiApp"],
      readonly: false
    )

    build_app(scheme: "TestCiApp")

    upload_to_testappio(
      api_token: "0db11f3c-d0d7-4b1c-8c76-8197063b74a5"
    )
  end
end
