platform :ios do
  desc "Build and upload to TestApp.io"
  lane :beta do
    puts "🔐 Using local AuthKey.p8 file"

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: File.expand_path("fastlane/AuthKey.p8")
    )

    match(
      type: "adhoc",
      api_key: api_key,
      git_url: "https://github.com/MohammedHamiid/ios-certificates.git",
      app_identifier: "com.benhamid.TestCiApp",
      readonly: false
    )

    build_app(
      scheme: "TestCiApp",
      export_method: "ad-hoc"
    )

    upload_to_testappio(
      api_token: "0db11f3c-d0d7-4b1c-8c76-8197063b74a5",
      app_id: "9QorGVmE7M"
    )
  end
end
