name: iOS Build & Upload to TestApp.io

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Fastlane
      env:
        TESTAPPIO_API_TOKEN: ${{ secrets.TESTAPPIO_API_TOKEN }}
      run: bundle exec fastlane ios beta
