name: iOS Build & Upload to TestApp.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle init || true
        bundle add fastlane fastlane-plugin-testappio || true

    - name: Run Fastlane
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        MATCH_GIT_PRIVATE_TOKEN: ${{ secrets.MATCH_GIT_PRIVATE_TOKEN }}
        TESTAPPIO_API_TOKEN: ${{ secrets.TESTAPPIO_API_TOKEN }}
        TESTAPPIO_APP_ID: ${{ secrets.TESTAPPIO_APP_ID }}
        APP_SCHEME: ${{ secrets.APP_SCHEME }}
      run: bundle exec fastlane ios beta
