name: iOS Build & Upload (with match)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler -v 2.6.9
          bundle _2.6.9_ install

      - name: Run Fastlane lane
        run: bundle _2.6.9_ exec fastlane ios beta
        env:
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          TESTAPPIO_API_TOKEN: ${{ secrets.TESTAPPIO_API_TOKEN }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
