
name: iOS CI & Upload to TestApp.io

on:
  push:
    branches: [ main ]  # Change if needed

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install Bundler
      run: gem install bundler

    - name: Install Fastlane
      run: gem install fastlane

    - name: Install dependencies (optional)
      run: bundle install || true

    - name: Build & Upload with Fastlane
      env:
        TESTAPP_API_KEY: ${{ secrets.TESTAPPIO_API_TOKEN }}
      run: fastlane beta
