name: iOS Build and Upload to TestApp.io

on:
  push:
    branches:
      - main     # أو فرعك الأساسي

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # أو أي نسخة روبي تناسب fastlane عندك
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Decrypt match certificates and profiles
        # لازم تكون مفعل secrets لتخزين ملفات match بشكل آمن
        run: bundle exec fastlane match adhoc --readonly
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Run fastlane beta lane
        run: bundle exec fastlane ios beta
        env:
          TESTAPPIO_API_TOKEN: ${{ secrets.TESTAPPIO_API_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}


