name: Build and Upload to TestApp.io

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: macos-latest
    env:
      TESTAPPIO_API_TOKEN: ${{ secrets.TESTAPPIO_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install fastlane
        run: gem install fastlane

      - name: Build and upload to TestApp.io
        run: fastlane ios upload_testappio

