jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Cache RubyGems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          gem install bundler -v 2.6.9
          bundle _2.6.9_ install

      - name: Configure Git credentials
        run: git config --global url."https://${{ secrets.MATCH_GIT_PRIVATE_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Run Fastlane lane (beta)
        run: bundle _2.6.9_ exec fastlane ios beta
        env:
          TESTAPPIO_API_TOKEN: ${{ secrets.TESTAPPIO_API_TOKEN }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
